export const meetups = [
  {
    id: 1,
    title: 'Конференция супер серьезных людей',
    description:
      'Самые серьезные люди мира соберуться, чтобы обсудить самые серьезные вещи',
    imageId: null,
    image: null,
    date: 1646208000000,
    organizer: 'Эл Гор',
    place: 'Pizza Hut',
    agenda: [
      {
        id: 11,
        startsAt: '08:00',
        endsAt: '09:00',
        type: 'registration',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 12,
        startsAt: '09:00',
        endsAt: '09:30',
        type: 'opening',
        title: 'Начало мероприятия',
        description: 'Разбор основных вопросов',
        speaker: 'Вася Пупкин',
        language: 'RU',
      },
      {
        id: 13,
        startsAt: '10:00',
        endsAt: '11:00',
        type: 'talk',
        title: 'Важные вещи',
        description: 'Описание мероприятия',
        speaker: 'абв',
        language: 'EN',
      },
    ],
  },
  {
    id: 2,
    title: 'Встреча фанатов Наруто',
    description: 'Встреча сильнейших шиноби всех деревень ниндзя',
    imageId: 1,
    image:
      'https://firebasestorage.googleapis.com/v0/b/meetups-ddc9b.appspot.com/o/covers%2Fmeetup_naruto_cover.jpg?alt=media&token=c0229277-561f-4ea0-879b-f3442ae555ff',
    date: 1650016800000,
    organizer: 'Udzumaki123',
    place: 'Деревня скрытая в листве',
    agenda: [
      {
        id: 21,
        startsAt: '10:00',
        endsAt: '10:30',
        type: 'registration',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 22,
        startsAt: '11:00',
        endsAt: '11:30',
        type: 'opening',
        title: 'Начало собрания каге',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 23,
        startsAt: '12:00',
        endsAt: '13:00',
        type: 'coffee',
        title: 'Перекус',
        description: 'Перерыв на онигири',
        speaker: null,
        language: null,
      },
      {
        id: 24,
        startsAt: '12:00',
        endsAt: '13:00',
        type: 'talk',
        title: 'Проблема быстрого затупления кунаев',
        description: 'Как сделать чтобы кунаи оставался острым дольше?',
        speaker: 'Хотаке Какаши',
        language: 'EN',
      },
      {
        id: 25,
        startsAt: '13:00',
        endsAt: '15:00',
        type: 'afterparty',
        title: 'Тусовка',
        description: 'бла бла бла',
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 3,
    title: 'Онлайн концерт Олега Газманова',
    description: 'Не пропусти стрим тысячелетия',
    imageId: null,
    image: null,
    date: 1644483600000,
    organizer: 'Олег Газманов',
    place: 'Интернет',
    agenda: null,
  },
  {
    id: 4,
    title: 'Приключение Финна и Джейка',
    description: 'Очередная захватывающая история',
    imageId: 4,
    image:
      'https://firebasestorage.googleapis.com/v0/b/meetups-ddc9b.appspot.com/o/covers%2Fmeetup_adventure_cover.jpg?alt=media&token=06d1cfcf-35ca-4f36-8267-eebf19ffa0aa',
    date: 1666260000000,
    organizer: 'Финн Парнишка и Джейк Пес',
    place: 'Какая-то пещера',
    agenda: [
      {
        id: 41,
        startsAt: '10:00',
        endsAt: '10:30',
        type: 'registration',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 42,
        startsAt: '11:00',
        endsAt: '11:30',
        type: 'opening',
        title: 'Приключение',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 43,
        startsAt: '12:00',
        endsAt: '13:00',
        type: 'break',
        title: 'Перекус бутерами',
        description: 'Перерыв на кофе',
        speaker: null,
        language: null,
      },
      {
        id: 44,
        startsAt: '12:00',
        endsAt: '13:00',
        type: 'talk',
        title: 'Важные вещи',
        description: 'Описание мероприятия',
        speaker: 'абв',
        language: 'EN',
      },
      {
        id: 45,
        startsAt: '13:00',
        endsAt: '15:00',
        type: 'afterparty',
        title: 'Тусовка',
        description: 'бла бла бла',
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 5,
    title: 'Встреча любителей игры в нарды',
    description: 'Может партеечку?',
    imageId: null,
    image: null,
    date: 1656601200000,
    organizer: 'Армяне',
    place: 'В том анекдоте',
    agenda: [
      {
        id: 41,
        startsAt: '10:00',
        endsAt: '10:30',
        type: 'registration',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 42,
        startsAt: '11:00',
        endsAt: '11:30',
        type: 'opening',
        title: 'Приключение',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 43,
        startsAt: '12:00',
        endsAt: '13:00',
        type: 'break',
        title: 'Перекус бутерами',
        description: 'Перерыв на кофе',
        speaker: null,
        language: null,
      },
      {
        id: 44,
        startsAt: '12:00',
        endsAt: '13:00',
        type: 'talk',
        title: 'Важные вещи',
        description: 'Описание мероприятия',
        speaker: 'абв',
        language: 'EN',
      },
      {
        id: 45,
        startsAt: '13:00',
        endsAt: '15:00',
        type: 'afterparty',
        title: 'Тусовка',
        description: 'бла бла бла',
        speaker: null,
        language: null,
      },
    ],
  },
];
