export const meetups = {
  1: {
    id: 1,
    title: 'Конференция супер серьезных людей',
    description:
      'Самые серьезные люди мира соберуться, чтобы обсудить самые серьезные вещи',
    imageId: null,
    image: null,
    date: 1640995200000,
    organizer: 'Эл Гор',
    place: 'Pizza Hut',
  },
  2: {
    id: 2,
    title: 'Встреча фанатов Наруто',
    description: 'Встреча сильнейших шиноби всех деревень ниндзя',
    imageId: null,
    image: null,
    date: 1640995200000,
    organizer: 'Udzumaki123',
    place: 'Деревня скрытая в листве',
  },
  3: {
    id: 3,
    title: 'Онлайн концерт Олега Газманова',
    description: 'Не пропусти стрим тысячелетия',
    imageId: null,
    image: null,
    date: 1640995200000,
    organizer: 'Олег Газманов',
    place: 'Интернет',
  },
  4: {
    id: 4,
    title: 'Приключение Финна и Джейка',
    description: 'Очередная захватывающая история',
    imageId: null,
    image: null,
    date: 1640995200000,
    organizer: 'Финн Парнишка и Джейк Пес',
    place: 'Какая-то пещера',
  },
  5: {
    id: 5,
    title: 'Встреча любителей игры в нарды',
    description: 'Может партеечку?',
    imageId: null,
    image: null,
    date: 1640995200000,
    organizer: 'Армяне',
    place: 'В том анекдоте',
  },
};
